// <auto-generated />
using System;
using Facial.Recognize.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Facial.Recognize.Core.Migrations
{
    [DbContext(typeof(TrainningFaceContext))]
    [Migration("20190912072219_AddCreatedAtColumnToInt")]
    partial class AddCreatedAtColumnToInt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Facial.Recognize.Core.Models.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<byte[]>("Image");

                    b.Property<string>("Label");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Faces");
                });
#pragma warning restore 612, 618
        }
    }
}
